version: '3'
services:
  tor-server:
    build: 
      context: ./tor-server
    image: tor-server
    networks:
      tor-net:
        aliases:
          - tor

  privoxy-server:
    build: 
      context: ./privoxy-server
    image: privoxy-server
    ports:
      - 8118:8118
    networks:
      - tor-net
    depends_on:
      - tor-server

networks:
  tor-net:
    driver: bridge
